# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Payment Confirmation

# Model Form Field configuration
form: $/octobro/banktransfer/models/paymentconfirmation/fields.yaml

# Model Class name
modelClass: Octobro\BankTransfer\Models\PaymentConfirmation

# Default redirect location
defaultRedirect: octobro/banktransfer/paymentconfirmation

# Create page
create:
    title: Create Payment Confirmation
    redirect: octobro/banktransfer/paymentconfirmation/update/:id
    redirectClose: octobro/banktransfer/paymentconfirmation

# Update page
update:
    title: Edit Payment Confirmation
    redirect: octobro/banktransfer/paymentconfirmation
    redirectClose: octobro/banktransfer/paymentconfirmation

# Preview page
preview:
    title: Preview Payment Confirmation
